### ISSUE TITLE
Maintainer access to Google analytics

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy-website#278]
Currently it seems that none of the website maintainers have access to the Google Analytics console

Its not clear whether a new account has been set up and whether we need to be provided access to that - @chalin perhaps you can now give us access ?

cc @mattklein123

**Comment by chalin** [comment]
I've added you both (@phlax and @mattklein123) as admins using your emails address that I got from [OWNERS](https://github.com/envoyproxy/envoy/blob/main/OWNERS.md). You should have received invites. Feel free to add other maintainers as Editors. Let me know when that is done; I may need to bump down your role to Editor some time (I'm still double checking policies on the CNCF side).

**Comment by phlax** [comment]
great thanks - i didnt receive an email, but i have access now

**Comment by chalin** [comment]
Just to be clear, I've granted you access to the GA4 property. I still don't have access to the UA property.

**Comment by phlax** [comment]
just getting up to speed - its a while since i looked at analytics

do you need something from us/someone to setup the UA tracking?

**Comment by chalin** [comment]
FYI, per CNCF policy, I'm setting your roles to Viewer.

> do you need something from us/someone to setup the UA tracking?

The UA site tag should be receiving events too since I've connected to it from the GA4 site tag. What I need is access to the UA property. I've sent out a few requests. In the end, if no one we know still has access to the UA property, we'll just work from the GA4 property. Eventually, the UA property will go away once Google stops supporting UA and drops the data.
